#!/bin/bash

# purpose: md2html exports a dir of md files into html using pandoc
# author: Jay Stanley (jss.place)
# updated: 2020-09-13

# requires the following args in positional order:
    # arg 1 specifies the dir of md files
    # arg 2 specifies the dir of the css file to use
    # both args must be absolute dir paths

echo '
███╗   ███╗██████╗ ██████╗ ██╗  ██╗████████╗███╗   ███╗██╗     
████╗ ████║██╔══██╗╚════██╗██║  ██║╚══██╔══╝████╗ ████║██║     
██╔████╔██║██║  ██║ █████╔╝███████║   ██║   ██╔████╔██║██║     
██║╚██╔╝██║██║  ██║██╔═══╝ ██╔══██║   ██║   ██║╚██╔╝██║██║     
██║ ╚═╝ ██║██████╔╝███████╗██║  ██║   ██║   ██║ ╚═╝ ██║███████╗
╚═╝     ╚═╝╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝╚══════╝
'

echo "INFO: Using md files in directory: $1"
if [ -d $1html ]
then
    echo "INFO: Subdirectory called 'html' already exists"
else
    echo "INFO: Creating subdirectory called 'html'"
    mkdir $1html
fi
echo "INFO: Creating html files in directory: $1html/"
for file in $1*.md
do
    filename=${file##*/}
    if [ -f $1html/${filename%.*}.html ]
    then
        echo "WARNING: ${filename%.*}.html already existed but overwriting it now"
        rm $1html/${filename%.*}.html
        pandoc -s --self-contained --resource-path=.:$1 -c $2*.css --metadata title="${filename%.*}" $file -o $1html/"${filename%.*}.html"
    else
        echo "INFO: Creating ${filename%.*}.html"
        pandoc -s --self-contained --resource-path=.:$1 -c $2*.css --metadata title="${filename%.*}" $file -o $1html/"${filename%.*}.html"
    fi
done
echo "INFO: All html files have been created"
